# Generated by Django 6.0.7 on 2026-07-13 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0004_engagement__llm_api_key_encrypted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PmoTaskStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tasks",
                    models.JSONField(
                        blank=True, default=list, verbose_name="タスク一覧"
                    ),
                ),
                (
                    "saved_at",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="保存日時(ISO)"
                    ),
                ),
                (
                    "store_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ストアハッシュ"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "engagement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmo_task_store",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pmo_task_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
