# Generated by Django 6.0.7 on 2026-07-13 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0004_engagement__llm_api_key_encrypted_and_more"),
        ("pmo_agent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PmoJsonStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("report", "報告生成・承認"),
                            ("kpi", "KPI・効果測定"),
                            ("proposal", "AI介入提案"),
                        ],
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ペイロード"
                    ),
                ),
                (
                    "saved_at",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="保存日時(ISO)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmo_json_stores",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pmo_json_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("engagement", "kind"),
                        name="uniq_pmo_json_store_engagement_kind",
                    )
                ],
            },
        ),
    ]
