# Generated by Django 6.0.7 on 2026-07-12 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0002_engagement_defect_ticket_types_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "定期"),
                            ("event", "同期後イベント"),
                            ("manual", "手動"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "実行中"),
                            ("success", "成功"),
                            ("failed", "失敗"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "findings_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="検知数"),
                ),
                (
                    "proposals_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="提案数"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, verbose_name="自律運転を有効にする"
                    ),
                ),
                (
                    "stagnant_spike_threshold",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="停滞急増の閾値(24h件数)"
                    ),
                ),
                (
                    "defect_spike_threshold",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="欠陥急増の閾値(24h件数)"
                    ),
                ),
                (
                    "overdue_threshold",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="期限超過の閾値(累計件数)"
                    ),
                ),
                (
                    "max_llm_calls_per_day",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="LLM呼び出し上限(日)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_settings",
                        to="engagements.engagement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("register_risk", "リスク登録"),
                            ("create_action", "改善アクション作成"),
                            ("draft_report", "報告書ドラフト作成"),
                            ("summary_only", "状況共有(登録なし)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(max_length=100, verbose_name="重複抑止キー"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="提案")),
                ("evidence", models.JSONField(default=dict, verbose_name="検知根拠")),
                ("body", models.TextField(blank=True, verbose_name="分析と提案内容")),
                (
                    "payload",
                    models.JSONField(default=dict, verbose_name="承認時の登録データ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "承認待ち"),
                            ("approved", "承認"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="判断メモ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_proposals",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="autopilot.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("engagement", "kind", "dedup_key"),
                        name="unique_pending_proposal",
                    )
                ],
            },
        ),
    ]
