# Generated by Django 6.0.7 on 2026-07-11 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0002_ticket_closed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OdcClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("function", "機能"),
                            ("assignment", "割付・初期化"),
                            ("checking", "チェック"),
                            ("algorithm", "アルゴリズム"),
                            ("timing", "タイミング・直列化"),
                            ("interface", "インターフェース"),
                            ("relationship", "関連"),
                            ("documentation", "ドキュメント"),
                        ],
                        max_length=30,
                        verbose_name="欠陥タイプ",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("design_conformance", "設計適合性"),
                            ("coverage", "カバレッジ"),
                            ("variation", "バリエーション"),
                            ("sequencing", "シーケンス"),
                            ("interaction", "相互作用"),
                            ("workload", "負荷・ストレス"),
                            ("regression", "回帰"),
                            ("configuration", "設定・環境"),
                        ],
                        max_length=30,
                        verbose_name="トリガー",
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("req_review", "要件レビュー"),
                            ("design_review", "設計レビュー"),
                            ("code_review", "コードレビュー"),
                            ("unit_test", "単体テスト"),
                            ("integration_test", "結合テスト"),
                            ("system_test", "システムテスト"),
                            ("acceptance_test", "受入テスト"),
                            ("production", "本番・運用"),
                        ],
                        max_length=30,
                        verbose_name="検出アクティビティ",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("critical", "致命的"),
                            ("major", "重大"),
                            ("moderate", "中程度"),
                            ("minor", "軽微"),
                        ],
                        max_length=30,
                        verbose_name="影響度",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("field", "チケットフィールド由来"),
                            ("llm", "LLM推定"),
                            ("manual", "手動"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="出所",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "レビュー待ち"),
                            ("confirmed", "確定済み"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="確定状態",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odc_classification",
                        to="tickets.ticket",
                    ),
                ),
            ],
        ),
    ]
