# Generated by Django 6.0.7 on 2026-07-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("engagements", "0002_engagement_defect_ticket_types_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField(verbose_name="週の開始日(月曜)")),
                ("body", models.TextField(verbose_name="要約本文")),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="集計指標"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_digests",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("engagement", "week_start"),
                        name="unique_digest_per_week",
                    )
                ],
            },
        ),
    ]
