# Generated by Django 6.0.7 on 2026-07-11 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0002_engagement_defect_ticket_types_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="リスク")),
                ("description", models.TextField(blank=True, verbose_name="内容")),
                (
                    "probability",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="発生確率(1-5)"
                    ),
                ),
                (
                    "impact",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="影響度(1-5)"
                    ),
                ),
                (
                    "measurement",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="測定方法"
                    ),
                ),
                (
                    "countermeasure",
                    models.TextField(blank=True, verbose_name="顕在化時の対策"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "識別"),
                            ("monitoring", "監視中"),
                            ("materialized", "顕在化"),
                            ("closed", "クローズ"),
                        ],
                        default="identified",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="対応期限"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ImprovementAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="アクション")),
                ("background", models.TextField(blank=True, verbose_name="背景・根拠")),
                (
                    "origin_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="起点(自由記述)"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="期限"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "計画"),
                            ("in_progress", "実行中"),
                            ("done", "完了"),
                            ("cancelled", "中止"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "effect_note",
                    models.TextField(blank=True, verbose_name="効果確認メモ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_actions",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="risks.riskitem",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="GeneralNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("risk_overdue", "リスク対応期限超過"),
                            ("action_overdue", "改善アクション期限超過"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(max_length=300, verbose_name="内容")),
                ("is_read", models.BooleanField(default=False, verbose_name="既読")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_notifications",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("engagement", "kind", "message"),
                        name="unique_general_notification",
                    )
                ],
            },
        ),
    ]
