# Generated by Django 6.0.7 on 2026-07-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalnotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("risk_overdue", "リスク対応期限超過"),
                    ("action_overdue", "改善アクション期限超過"),
                    ("agent_proposal", "エージェント提案"),
                ],
                max_length=30,
            ),
        ),
    ]
