# Generated by Django 6.0.7 on 2026-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risks", "0002_alter_generalnotification_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskitem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technical", "技術"),
                    ("schedule", "スケジュール"),
                    ("cost", "コスト"),
                    ("resource", "リソース"),
                    ("external", "外部"),
                    ("compliance", "コンプライアンス・規制"),
                ],
                max_length=20,
                verbose_name="カテゴリ",
            ),
        ),
        migrations.AddField(
            model_name="riskitem",
            name="response_strategy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("avoid", "回避"),
                    ("transfer", "転嫁"),
                    ("mitigate", "軽減"),
                    ("accept", "受容"),
                ],
                max_length=20,
                verbose_name="対応戦略",
            ),
        ),
        migrations.AddField(
            model_name="riskitem",
            name="trigger",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="トリガー・予兆"
            ),
        ),
    ]
