# Generated by Django 6.0.7 on 2026-07-11 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0002_engagement_defect_ticket_types_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TpiKeyArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="キーエリア名"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="説明"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="表示順"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TpiAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "実施中"), ("final", "確定")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("suggestion", models.TextField(blank=True, verbose_name="改善提言")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tpi_assessments",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TpiCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("controlled", "コントロールド"),
                            ("efficient", "エフィシェント"),
                            ("optimizing", "オプティマイジング"),
                        ],
                        max_length=20,
                        verbose_name="成熟度レベル",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=500, verbose_name="チェックポイント"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "key_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="tpi.tpikeyarea",
                    ),
                ),
            ],
            options={
                "ordering": ["key_area", "level", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TpiAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("met", "充足"),
                            ("not_met", "未充足"),
                            ("na", "対象外"),
                        ],
                        default="not_met",
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="メモ"),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="tpi.tpiassessment",
                    ),
                ),
                (
                    "checkpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tpi.tpicheckpoint",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment", "checkpoint"),
                        name="unique_answer_per_checkpoint",
                    )
                ],
            },
        ),
    ]
