# Generated by Django 6.0.7 on 2026-07-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StagnationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stale_after_days",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="更新なし停滞判定(日)"
                    ),
                ),
                (
                    "notify_on_overdue",
                    models.BooleanField(
                        default=True, verbose_name="期限超過も検知する"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stagnation_rule",
                        to="engagements.engagement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("jira", "JIRA"), ("redmine", "Redmine")],
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="表示名")),
                ("base_url", models.URLField(verbose_name="接続先URL")),
                (
                    "project_key",
                    models.CharField(max_length=100, verbose_name="プロジェクトキー"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ユーザー名/メール"
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="APIトークン"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="同期を有効にする"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終同期日時"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_sources",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(max_length=50, verbose_name="元チケットID"),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="元チケットURL"),
                ),
                ("summary", models.CharField(max_length=500, verbose_name="概要")),
                ("description", models.TextField(blank=True, verbose_name="本文")),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="状態(元システム)"
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="完了済み"),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="優先度(元システム)"
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="種別(元システム)"
                    ),
                ),
                (
                    "assignee_name",
                    models.CharField(blank=True, max_length=200, verbose_name="担当者"),
                ),
                (
                    "reporter_name",
                    models.CharField(blank=True, max_length=200, verbose_name="報告者"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="期限"),
                ),
                (
                    "source_created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="元システムでの作成日時"
                    ),
                ),
                (
                    "source_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="元システムでの更新日時"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="元データ"),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="取込日時"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="tickets.ticketsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-source_updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "実行中"),
                            ("success", "成功"),
                            ("failed", "失敗"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                (
                    "tickets_synced",
                    models.PositiveIntegerField(default=0, verbose_name="同期件数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="エラー内容"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="tickets.ticketsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("stagnant", "停滞"), ("overdue", "期限超過")],
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                ("message", models.CharField(max_length=300, verbose_name="内容")),
                ("is_read", models.BooleanField(default=False, verbose_name="既読")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "kind"),
                        name="unique_notification_per_ticket_kind",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="unique_ticket_per_source"
            ),
        ),
    ]
