# Generated by Django 6.0.7 on 2026-07-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="クローズ日時"
            ),
        ),
    ]
