# Generated by Django 6.0.7 on 2026-07-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_remove_api_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketStatusTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="変更前ステータス"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(max_length=100, verbose_name="変更後ステータス"),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="発生日時")),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_transitions",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "occurred_at", "to_status"),
                        name="unique_status_transition",
                    )
                ],
            },
        ),
    ]
