# Generated by Django 6.0.7 on 2026-07-11 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0002_engagement_defect_ticket_types_and_more"),
        ("tickets", "0006_ticketstatustransition"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "メール"),
                            ("slack_webhook", "Slack Incoming Webhook"),
                        ],
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        max_length=500, verbose_name="宛先(メールアドレス/Webhook URL)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channels",
                        to="engagements.engagement",
                    ),
                ),
            ],
        ),
    ]
