# Generated by Django 6.0.7 on 2026-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_notificationchannel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketsource",
            name="kind",
            field=models.CharField(
                choices=[
                    ("jira", "JIRA"),
                    ("redmine", "Redmine"),
                    ("internal", "このシステム"),
                ],
                max_length=20,
                verbose_name="種別",
            ),
        ),
    ]
