# Generated by Django 6.0.7 on 2026-07-11 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="案件名")),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="概要"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "進行中"),
                            ("on_hold", "保留中"),
                            ("completed", "完了"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="進捗率(%)"
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI API"),
                            ("claude", "Claude API"),
                            ("ollama", "ローカルLLM (Ollama)"),
                        ],
                        default="ollama",
                        max_length=20,
                        verbose_name="既定LLMプロバイダ",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=300, verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="発生日時"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
