# Generated by Django 6.0.7 on 2026-07-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="defect_ticket_types",
            field=models.JSONField(
                blank=True, default=list, verbose_name="欠陥として扱う種別"
            ),
        ),
        migrations.AddField(
            model_name="engagement",
            name="size_metric_name",
            field=models.CharField(
                blank=True,
                help_text="例: テストケース数, KLOC",
                max_length=50,
                verbose_name="規模の単位",
            ),
        ),
        migrations.AddField(
            model_name="engagement",
            name="size_metric_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="規模の値",
            ),
        ),
    ]
