# Generated by Django 6.0.7 on 2026-07-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0002_engagement_defect_ticket_types_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="llm_model",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="既定モデル"
            ),
        ),
    ]
