# Generated by Django 6.0.7 on 2026-07-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0003_engagement_llm_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="_llm_api_key_encrypted",
            field=models.TextField(
                blank=True,
                db_column="llm_api_key_encrypted",
                verbose_name="LLM APIキー(暗号化)",
            ),
        ),
        migrations.AddField(
            model_name="engagement",
            name="_llm_org_id_encrypted",
            field=models.TextField(
                blank=True,
                db_column="llm_org_id_encrypted",
                verbose_name="Organization ID(暗号化)",
            ),
        ),
        migrations.AddField(
            model_name="engagement",
            name="_llm_project_id_encrypted",
            field=models.TextField(
                blank=True,
                db_column="llm_project_id_encrypted",
                verbose_name="Project ID(暗号化)",
            ),
        ),
    ]
