# Generated by Django 6.0.7 on 2026-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0004_engagement__llm_api_key_encrypted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="monthly_token_limit",
            field=models.PositiveIntegerField(
                default=0, verbose_name="月間トークン上限(0=無制限)"
            ),
        ),
    ]
