# Generated by Django 6.0.7 on 2026-07-11 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0002_engagement_defect_ticket_types_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ゲート名")),
                ("criteria", models.JSONField(default=dict, verbose_name="判定条件")),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("pending", "判定前"),
                            ("passed", "合格"),
                            ("failed", "不合格"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("judged_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, verbose_name="判定コメント")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_gates",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "judged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("master", "マスターテスト計画"),
                            ("level", "レベルテスト計画"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                (
                    "test_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="対象テストレベル"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="本文")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "ドラフト"), ("approved", "承認済み")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_plans",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestProgressEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_level",
                    models.CharField(max_length=50, verbose_name="テストレベル"),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "planned_cases",
                    models.PositiveIntegerField(default=0, verbose_name="計画累計"),
                ),
                (
                    "executed_cases",
                    models.PositiveIntegerField(default=0, verbose_name="実行累計"),
                ),
                (
                    "passed_cases",
                    models.PositiveIntegerField(default=0, verbose_name="合格累計"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="メモ"),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_progress",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ["test_level", "date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("engagement", "test_level", "date"),
                        name="unique_progress_per_day",
                    )
                ],
            },
        ),
    ]
